const studioAddress =
  'Shop No. 155, Basement, near Apollo Pharmacy, Main HUDA Market, Sector 31, Gurugram, Haryana 122001';

export const locationPages = [
  {
    slug: 'sector-31',
    name: 'Sector 31',
    title: 'Tattoo Studio in Sector 31, Gurugram',
    metaTitle: 'Tattoo Studio in Sector 31 Gurugram | Divine Ink',
    description: 'Visit Divine Ink Tattoos & Piercing Studio in Sector 31 Gurugram for custom tattoos, cover-ups and professional piercing by appointment.',
    eyebrow: 'Our home neighbourhood · HUDA Market',
    intro: `Divine Ink is based at ${studioAddress}, making this the studio’s dedicated local page for clients in Sector 31.`,
    local: 'The studio is in Main HUDA Market, close to Apollo Pharmacy. Clients can discuss custom concepts, tattoo placement, existing tattoo cover-ups and suitable piercing options before confirming an appointment.',
    travel: 'If you are coming from elsewhere in Gurugram, ask the team for the current map pin before travelling. Market traffic and parking conditions can vary during busy periods.',
    faq: [
      ['Where is Divine Ink in Sector 31?', `The studio is at ${studioAddress}. Confirm the map pin on WhatsApp before your appointment.`],
      ['Should I book before visiting?', 'Yes. Booking first gives the team time to review references and confirm artist availability.'],
    ],
    related: ['sector-14', 'sector-46', 'huda-city-centre'],
  },
  {
    slug: 'huda-city-centre',
    name: 'HUDA City Centre',
    title: 'Tattoo Studio near HUDA City Centre',
    metaTitle: 'Tattoo Studio near HUDA City Centre | Divine Ink',
    description: 'Looking for a tattoo studio near HUDA City Centre? Book Divine Ink in Sector 31 Gurugram for custom tattoos and professional piercing.',
    eyebrow: 'Central Gurugram · appointment-led studio',
    intro: 'Clients around HUDA City Centre can book tattoo and piercing consultations at Divine Ink’s established Sector 31 studio.',
    local: 'A consultation helps translate an inspiration image into a design suited to the chosen body area. The team discusses scale, detail, placement and session expectations rather than promising a result from a reference alone.',
    travel: 'Divine Ink operates from one studio in Sector 31, not a branch at the metro station. Request the studio map pin and allow for changing central Gurugram traffic.',
    faq: [
      ['Is Divine Ink inside HUDA City Centre?', 'No. Divine Ink is located in Sector 31 HUDA Market and serves clients travelling from the HUDA City Centre area.'],
      ['Can I send my tattoo idea before visiting?', 'Yes. Send a clear reference, preferred placement and approximate size on WhatsApp for an initial discussion.'],
    ],
    related: ['sector-31', 'sushant-lok', 'mg-road'],
  },
  {
    slug: '32nd-avenue',
    name: '32nd Avenue',
    title: 'Tattoo Studio near 32nd Avenue, Gurugram',
    metaTitle: 'Tattoo Studio near 32nd Avenue Gurugram | Divine Ink',
    description: 'Book a tattoo consultation near 32nd Avenue Gurugram at Divine Ink, Sector 31. Custom tattoos, cover-ups and piercing by appointment.',
    eyebrow: 'Near central Gurugram · custom-led work',
    intro: 'For clients visiting or living around 32nd Avenue, Divine Ink offers appointment-led tattoo and piercing services from nearby Sector 31.',
    local: 'Custom work is planned around personal meaning and long-term readability. Fine-line, minimal, portrait, black-and-grey and colour references are assessed for a practical size before the stencil is approved.',
    travel: 'The studio is not located inside 32nd Avenue. It is based in Sector 31 HUDA Market, so confirm directions and appointment time with the team before setting out.',
    faq: [
      ['Does Divine Ink have a branch at 32nd Avenue?', 'No. The studio serves the 32nd Avenue area from its Sector 31 HUDA Market address.'],
      ['Can I book a same-day appointment?', 'Availability varies. Contact the studio first so the team can assess the work and confirm a suitable slot.'],
    ],
    related: ['sector-31', 'sector-14', 'mg-road'],
  },
  {
    slug: 'cyber-city',
    name: 'Cyber City',
    title: 'Tattoo Studio near Cyber City, Gurugram',
    metaTitle: 'Tattoo Studio near Cyber City Gurugram | Divine Ink',
    description: 'Find custom tattoo and professional piercing appointments near Cyber City Gurugram at Divine Ink Tattoos in Sector 31 HUDA Market.',
    eyebrow: 'Serving Cyber City professionals',
    intro: 'Divine Ink welcomes clients from Cyber City who want a planned tattoo consultation or professional piercing appointment in Gurugram.',
    local: 'The team can review references digitally before a studio visit, which is useful when scheduling around office hours. Final placement, scale, stencil and feasibility are always confirmed in person.',
    travel: 'Divine Ink is a single-location studio in Sector 31. Cyber City clients should account for peak-hour traffic and confirm the appointment before travelling.',
    faq: [
      ['Is an evening consultation available for Cyber City clients?', 'Appointment times depend on the studio schedule. Contact Divine Ink to check the current available slots.'],
      ['Can a design be approved entirely online?', 'References can be reviewed online, but final sizing, placement and stencil approval happen at the studio.'],
    ],
    related: ['udyog-vihar', 'dlf-phase-2', 'dlf-phase-3'],
  },
  {
    slug: 'mg-road',
    name: 'MG Road',
    title: 'Tattoo Studio near MG Road, Gurugram',
    metaTitle: 'Tattoo Studio near MG Road Gurugram | Divine Ink',
    description: 'Book a tattoo or piercing appointment near MG Road Gurugram at Divine Ink Studio, located in Sector 31 HUDA Market.',
    eyebrow: 'Central access · personal consultations',
    intro: 'People around MG Road can plan custom tattoos, cover-ups and piercings with Divine Ink at its Sector 31 Gurugram studio.',
    local: 'The consultation covers design intent, placement, size and realistic session requirements. Cover-up enquiries should include clear photographs of the existing tattoo in natural light.',
    travel: 'The studio is in Sector 31 rather than on MG Road. Ask for the current map pin and plan travel outside the busiest road hours where possible.',
    faq: [
      ['How do I book from MG Road?', 'Call or WhatsApp the studio with the service, preferred date and any relevant reference images.'],
      ['Does Divine Ink accept walk-ins?', 'Advance contact is recommended because consultation and artist availability can change.'],
    ],
    related: ['huda-city-centre', 'sushant-lok', 'dlf-phase-1'],
  },
  {
    slug: 'dlf-phase-1',
    name: 'DLF Phase 1',
    title: 'Tattoo Studio near DLF Phase 1, Gurugram',
    metaTitle: 'Tattoo Studio near DLF Phase 1 | Divine Ink Gurugram',
    description: 'Plan a custom tattoo near DLF Phase 1 at Divine Ink Gurugram. Get reference review, placement guidance and appointment-led tattooing.',
    eyebrow: 'Custom tattoos for DLF Phase 1',
    intro: 'Divine Ink serves DLF Phase 1 residents from its dedicated Sector 31 studio with custom tattoo and piercing appointments.',
    local: 'Tattoo ideas are adapted to the body rather than copied unchanged. The artist evaluates detail, negative space and contrast so the composition remains clear at the intended scale.',
    travel: 'There is no Divine Ink branch in DLF Phase 1. Confirm the Sector 31 studio location and travel arrangements before the appointment.',
    faq: [
      ['Can I get a price estimate before travelling from DLF Phase 1?', 'Send the reference, placement and approximate size. A final quote may require an in-person assessment.'],
      ['What should I bring to a tattoo consultation?', 'Bring high-quality references and any exact spelling, dates or symbols that the design must contain.'],
    ],
    related: ['golf-course-road', 'sushant-lok', 'mg-road'],
  },
  {
    slug: 'dlf-phase-2',
    name: 'DLF Phase 2',
    title: 'Tattoo Studio near DLF Phase 2, Gurugram',
    metaTitle: 'Tattoo Studio near DLF Phase 2 | Divine Ink Gurugram',
    description: 'Book custom tattoo and professional piercing services near DLF Phase 2 at Divine Ink Tattoos, Sector 31 Gurugram.',
    eyebrow: 'Serving DLF Phase 2 by appointment',
    intro: 'Clients from DLF Phase 2 can consult Divine Ink for carefully planned tattoos and anatomy-aware piercing services.',
    local: 'Tattoo appointments begin with reference and placement review. Piercing appointments include suitability checks and practical aftercare guidance based on the selected placement.',
    travel: 'Divine Ink operates in Sector 31 HUDA Market. For a smoother visit from DLF Phase 2, request the map pin and avoid arriving without a confirmed slot.',
    faq: [
      ['Are tattoo and piercing services at the same studio?', 'Yes. Both are offered at Divine Ink’s Sector 31 studio, subject to appointment availability.'],
      ['Can I bring a friend to the consultation?', 'Ask the team when booking, as space and appointment conditions may vary.'],
    ],
    related: ['cyber-city', 'dlf-phase-3', 'udyog-vihar'],
  },
  {
    slug: 'dlf-phase-3',
    name: 'DLF Phase 3',
    title: 'Tattoo Studio near DLF Phase 3, Gurugram',
    metaTitle: 'Tattoo Studio near DLF Phase 3 | Divine Ink Gurugram',
    description: 'Contact Divine Ink for tattoo and piercing appointments near DLF Phase 3 Gurugram, served from the Sector 31 HUDA Market studio.',
    eyebrow: 'Thoughtful design · clear booking',
    intro: 'Divine Ink offers DLF Phase 3 clients a consultation-first approach for tattoos and suitable body piercings.',
    local: 'For tattoos, the team reviews whether the requested detail is appropriate for the size and body placement. For piercings, anatomy and healing considerations are discussed before proceeding.',
    travel: 'The studio is in Sector 31 and does not claim a DLF Phase 3 branch. Contact Divine Ink for directions and current availability.',
    faq: [
      ['How early should I contact the studio?', 'Contact the team as soon as you know the preferred service and date, especially for detailed or larger tattoo work.'],
      ['Are reference images accepted on WhatsApp?', 'Yes. Clear reference images help with the initial discussion, but do not replace in-person assessment.'],
    ],
    related: ['cyber-city', 'dlf-phase-2', 'udyog-vihar'],
  },
  {
    slug: 'sushant-lok',
    name: 'Sushant Lok',
    title: 'Tattoo Studio near Sushant Lok, Gurugram',
    metaTitle: 'Tattoo Studio near Sushant Lok | Divine Ink Gurugram',
    description: 'Explore custom tattoo, cover-up and piercing appointments near Sushant Lok at Divine Ink Tattoos in Sector 31 Gurugram.',
    eyebrow: 'Personal designs for Sushant Lok',
    intro: 'Sushant Lok clients can book a focused design or piercing consultation at Divine Ink’s Sector 31 studio.',
    local: 'The studio works across minimal, fine-line, portrait, sleeve, colour and black-and-grey directions. Each concept is assessed individually; style labels do not replace good placement and scale planning.',
    travel: 'Divine Ink is based in Sector 31. Confirm the appointment and destination pin before travelling from Sushant Lok.',
    faq: [
      ['Can an old tattoo be assessed for a cover-up?', 'Yes. Send clear photos first, then visit for an in-person assessment of pigment, size and skin texture.'],
      ['Do small tattoos need a consultation?', 'Yes. Small designs still require checks for line spacing, readability and suitable placement.'],
    ],
    related: ['huda-city-centre', 'golf-course-road', 'dlf-phase-1'],
  },
  {
    slug: 'golf-course-road',
    name: 'Golf Course Road',
    title: 'Tattoo Studio near Golf Course Road, Gurugram',
    metaTitle: 'Tattoo Studio near Golf Course Road | Divine Ink',
    description: 'Book a custom tattoo consultation near Golf Course Road Gurugram with Divine Ink, an appointment-led studio in Sector 31.',
    eyebrow: 'Serving Golf Course Road clients',
    intro: 'Divine Ink welcomes Golf Course Road clients seeking original tattoo planning, cover-up assessment or professional piercing.',
    local: 'Larger concepts such as portraits and sleeves may need a dedicated consultation and multiple sessions. The team explains composition, session sequence and aftercare before work begins.',
    travel: 'Appointments take place at the Sector 31 HUDA Market studio. Allow for variable traffic between Golf Course Road and central Gurugram.',
    faq: [
      ['Can a sleeve tattoo be completed in one appointment?', 'Sleeves are usually planned over multiple sessions according to scale, detail and healing requirements.'],
      ['Is a consultation fee required?', 'Contact the studio for its current booking and consultation policy.'],
    ],
    related: ['dlf-phase-1', 'sushant-lok', 'sector-46'],
  },
  {
    slug: 'sohna-road',
    name: 'Sohna Road',
    title: 'Tattoo Studio near Sohna Road, Gurugram',
    metaTitle: 'Tattoo Studio near Sohna Road Gurugram | Divine Ink',
    description: 'Plan custom tattoos and professional piercing near Sohna Road with Divine Ink Tattoos, located in Sector 31 Gurugram.',
    eyebrow: 'Serving south Gurugram',
    intro: 'Clients travelling from Sohna Road can arrange a tattoo or piercing consultation with Divine Ink before visiting Sector 31.',
    local: 'Sharing references in advance helps the team identify the style, likely scale and whether an in-person consultation is needed before booking the procedure itself.',
    travel: 'Divine Ink has one studio in Sector 31, not a Sohna Road outlet. Confirm the map pin and allow sufficient travel time for your booked appointment.',
    faq: [
      ['Can I combine consultation and tattooing in one visit?', 'That depends on design complexity and artist availability. Confirm the appointment type before travelling.'],
      ['What details should I send on WhatsApp?', 'Send the reference, body placement, approximate size and preferred appointment date.'],
    ],
    related: ['sector-46', 'sector-31', 'huda-city-centre'],
  },
  {
    slug: 'sector-14',
    name: 'Sector 14',
    title: 'Tattoo Studio near Sector 14, Gurugram',
    metaTitle: 'Tattoo Studio near Sector 14 Gurugram | Divine Ink',
    description: 'Looking for a tattoo studio near Sector 14 Gurugram? Book custom tattoo and piercing services at Divine Ink in Sector 31.',
    eyebrow: 'Nearby studio · individual planning',
    intro: 'Divine Ink serves Sector 14 clients from its nearby Sector 31 HUDA Market location with consultations arranged before the visit.',
    local: 'From meaningful lettering to larger custom compositions, the team checks spelling, reference quality, scale and body placement before confirming a stencil.',
    travel: 'The studio is in Sector 31 rather than Sector 14. Contact Divine Ink for the correct pin and current booking availability.',
    faq: [
      ['Does Divine Ink offer name tattoos?', 'Yes. Lettering style, spelling, spacing and a size suitable for long-term readability are reviewed first.'],
      ['Where is the actual studio?', `The only listed studio address is ${studioAddress}.`],
    ],
    related: ['sector-31', '32nd-avenue', 'palam-vihar'],
  },
  {
    slug: 'sector-46',
    name: 'Sector 46',
    title: 'Tattoo Studio near Sector 46, Gurugram',
    metaTitle: 'Tattoo Studio near Sector 46 Gurugram | Divine Ink',
    description: 'Book tattoo and piercing appointments near Sector 46 Gurugram with Divine Ink Tattoos & Piercing Studio in Sector 31.',
    eyebrow: 'Serving Sector 46 residents',
    intro: 'Sector 46 residents can visit Divine Ink in Sector 31 for planned custom tattoo and professional piercing appointments.',
    local: 'The team discusses healed-result expectations and aftercare as part of the service. Designs are adjusted when requested detail would not remain clear at a small scale.',
    travel: 'Appointments are completed at the Sector 31 HUDA Market studio. Confirm the booking before travelling from Sector 46.',
    faq: [
      ['Can I request a fine-line tattoo?', 'Yes. The artist will recommend a size and spacing that supports a clear healed result.'],
      ['Does Divine Ink provide aftercare guidance?', 'Yes. Practical aftercare instructions are discussed for tattoos and piercings.'],
    ],
    related: ['sector-31', 'sohna-road', 'golf-course-road'],
  },
  {
    slug: 'palam-vihar',
    name: 'Palam Vihar',
    title: 'Tattoo Studio near Palam Vihar, Gurugram',
    metaTitle: 'Tattoo Studio near Palam Vihar Gurugram | Divine Ink',
    description: 'Contact Divine Ink for custom tattoo, cover-up and piercing appointments near Palam Vihar, served from Sector 31 Gurugram.',
    eyebrow: 'Consult before travelling',
    intro: 'Palam Vihar clients can send tattoo references or piercing enquiries to Divine Ink before arranging a visit to Sector 31.',
    local: 'Advance review is especially useful for portrait references, cover-ups and larger custom pieces. The team can explain what must be assessed in person and what information to bring.',
    travel: 'Divine Ink does not operate a Palam Vihar branch. All appointments take place at the studio’s verified Sector 31 address.',
    faq: [
      ['Can cover-up suitability be confirmed from a photo?', 'A photo supports initial guidance, but final cover-up feasibility needs an in-person assessment.'],
      ['Can I call instead of using WhatsApp?', 'Yes. Use +91 84457 02782 to discuss availability.'],
    ],
    related: ['sector-14', 'udyog-vihar', 'sector-31'],
  },
  {
    slug: 'udyog-vihar',
    name: 'Udyog Vihar',
    title: 'Tattoo Studio near Udyog Vihar, Gurugram',
    metaTitle: 'Tattoo Studio near Udyog Vihar Gurugram | Divine Ink',
    description: 'Book tattoo and piercing consultations near Udyog Vihar at Divine Ink, a custom tattoo studio in Sector 31 Gurugram.',
    eyebrow: 'Flexible enquiry · confirmed appointments',
    intro: 'Professionals and residents around Udyog Vihar can contact Divine Ink in advance to plan tattoo or piercing appointments.',
    local: 'References can be shared before the visit to clarify the intended style and scope. The physical consultation confirms body placement, practical scale and any anatomy-related considerations.',
    travel: 'Divine Ink operates only from Sector 31 HUDA Market. Plan around busy commuting periods and wait for appointment confirmation before travelling.',
    faq: [
      ['Can I arrange an appointment around work hours?', 'Share your preferred date and time with the studio; availability depends on the current booking schedule.'],
      ['Is the Sector 31 studio the only location?', 'Yes. These area pages describe communities served by the single Sector 31 studio, not separate branches.'],
    ],
    related: ['cyber-city', 'dlf-phase-2', 'palam-vihar'],
  },
];

export const locationPageMap = new Map(
  locationPages.map((location) => [location.slug, location]),
);

