const tattooConsultation =
  'Every appointment starts with a review of the reference, body placement, practical size and expected level of detail. The final design and stencil are confirmed at the Sector 31 studio before tattooing begins.';

const piercingConsultation =
  'Placement is assessed against your anatomy before the piercing begins. Fresh consumables, clear preparation and practical aftercare guidance are part of every appointment at the Sector 31 studio.';

export const servicePages = [
  {
    slug: 'custom-tattoos',
    name: 'Custom Tattoos',
    title: 'Custom Tattoos in Gurugram',
    metaTitle: 'Custom Tattoo Artist in Gurugram | Divine Ink',
    description: 'Plan a custom tattoo in Gurugram with Divine Ink. Get design consultation, placement guidance and appointment-led tattooing in Sector 31.',
    eyebrow: 'Original concepts · considered placement',
    intro: 'A custom tattoo should be built around your story, body placement and visual preferences—not copied without thought from a catalogue.',
    overview: 'At Divine Ink Tattoos & Piercing Studio, custom tattoo planning begins by identifying what the design needs to communicate. References are used to understand style, composition and mood, then adjusted for the available skin area and long-term readability.',
    planning: tattooConsultation,
    care: 'Custom work can be small or developed across multiple sessions. Session planning depends on scale, detail, colour and how the design follows the body.',
    highlights: ['Original concept development', 'Placement and scale planning', 'Black-and-grey or colour options', 'Clear session and aftercare guidance'],
    related: ['fine-line-tattoos', 'black-grey-tattoos', 'sleeve-tattoos'],
  },
  {
    slug: 'name-tattoos',
    name: 'Name Tattoos',
    title: 'Name Tattoos in Gurugram',
    metaTitle: 'Name Tattoo Artist in Gurugram | Divine Ink',
    description: 'Book a personalised name tattoo in Gurugram. Divine Ink plans lettering, placement and spacing for clean, readable results in Sector 31.',
    eyebrow: 'Personal lettering · meaningful details',
    intro: 'Name tattoos can mark a relationship, memory or personal milestone, but the lettering must remain clear and balanced after healing.',
    overview: 'We help clients compare script, serif, handwritten and minimal lettering directions before selecting a final style. Decorative elements are added only when they support the name rather than reduce readability.',
    planning: 'The artist checks spelling, capitalisation, spacing and orientation with you before the stencil is applied. Fine scripts may need a larger size than expected so individual strokes do not crowd together over time.',
    care: 'Placement is chosen around visibility, movement and the natural line of the body. Bring the exact spelling and any date or symbol that must be included.',
    highlights: ['Spelling and typography checks', 'Readable size recommendations', 'Dates, initials and small symbols', 'Personalised stencil confirmation'],
    related: ['fine-line-tattoos', 'minimal-tattoos', 'custom-tattoos'],
  },
  {
    slug: 'fine-line-tattoos',
    name: 'Fine Line Tattoos',
    title: 'Fine Line Tattoos in Gurugram',
    metaTitle: 'Fine Line Tattoo Artist Gurugram | Divine Ink',
    description: 'Get a fine line tattoo in Gurugram with careful sizing, clean line planning and placement guidance at Divine Ink Tattoos, Sector 31.',
    eyebrow: 'Delicate lines · deliberate sizing',
    intro: 'Fine line tattoos rely on restraint and precision, but successful work also depends on choosing a size that can heal and age clearly.',
    overview: 'Divine Ink plans fine line concepts around line spacing, skin movement and the amount of detail requested. Botanical forms, symbols, small illustrations and simple lettering are adjusted rather than compressed into an unsuitable scale.',
    planning: tattooConsultation,
    care: 'Fresh fine line tattoos may look sharper than healed work. We explain realistic expectations, aftercare and when a healed review may be useful.',
    highlights: ['Clean, simplified compositions', 'Placement-led line spacing', 'Small botanical and symbolic work', 'Realistic healed-result guidance'],
    related: ['minimal-tattoos', 'name-tattoos', 'custom-tattoos'],
  },
  {
    slug: 'black-grey-tattoos',
    name: 'Black & Grey Tattoos',
    title: 'Black & Grey Tattoos in Gurugram',
    metaTitle: 'Black & Grey Tattoo Artist Gurugram | Divine Ink',
    description: 'Book black and grey tattoo work in Gurugram at Divine Ink. Plan contrast, shading, placement and sessions with artists in Sector 31.',
    eyebrow: 'Contrast · depth · controlled shading',
    intro: 'Black and grey tattooing uses tonal contrast to create depth without colour, from soft illustrative pieces to high-detail realism.',
    overview: 'We evaluate the reference for clear focal points, readable dark areas and enough open skin to preserve contrast. The design is adapted to the placement so shadows support the form instead of turning into an undifferentiated dark patch.',
    planning: tattooConsultation,
    care: 'Larger or highly detailed black and grey work may be divided into sessions. A healed result depends on controlled execution, appropriate scale and consistent aftercare.',
    highlights: ['Balanced black and grey values', 'Soft shading and bold contrast', 'Realism and illustrative options', 'Large-piece session planning'],
    related: ['portrait-tattoos', 'sleeve-tattoos', 'cover-up-tattoos'],
  },
  {
    slug: 'colour-tattoos',
    name: 'Colour Tattoos',
    title: 'Colour Tattoos in Gurugram',
    metaTitle: 'Colour Tattoo Artist in Gurugram | Divine Ink',
    description: 'Plan a colour tattoo in Gurugram with palette, contrast, placement and aftercare guidance at Divine Ink Tattoos in Sector 31.',
    eyebrow: 'Purposeful palettes · lasting contrast',
    intro: 'A strong colour tattoo needs more than bright pigments; it needs a palette with enough contrast to keep the design readable.',
    overview: 'Divine Ink selects colour relationships around the artwork, skin area and desired visual intensity. We avoid adding unnecessary shades that make a compact design visually crowded and discuss where outlines or darker values are needed.',
    planning: tattooConsultation,
    care: 'Sun exposure can affect tattoo colour over time. After healing, sensible sun protection and skin care help preserve the appearance of the work.',
    highlights: ['Coordinated colour palettes', 'Contrast and outline planning', 'Watercolour and illustrative options', 'Long-term colour-care guidance'],
    related: ['custom-tattoos', 'religious-tattoos', 'sleeve-tattoos'],
  },
  {
    slug: 'portrait-tattoos',
    name: 'Portrait Tattoos',
    title: 'Portrait Tattoos in Gurugram',
    metaTitle: 'Portrait Tattoo Artist in Gurugram | Divine Ink',
    description: 'Plan a portrait tattoo in Gurugram using a clear reference, suitable placement and realistic scale at Divine Ink Tattoos, Sector 31.',
    eyebrow: 'Reference quality · likeness · expression',
    intro: 'Portrait tattoos depend on reference quality, sufficient size and careful value structure to preserve recognisable features.',
    overview: 'We review whether the photograph has usable focus, lighting and facial detail before accepting it as the main reference. Cropping and background choices are planned to keep attention on the person, pet or memorial subject.',
    planning: 'Portraits cannot be responsibly reduced to every requested size. The artist recommends a scale that allows the eyes, mouth, hair and shadow transitions to remain distinct after healing.',
    care: 'Bring the highest-resolution original photograph available rather than a screenshot or filtered image. Complex portraits may require a dedicated consultation and longer session.',
    highlights: ['Reference photograph assessment', 'Likeness-focused composition', 'Black-and-grey portrait planning', 'Memorial and personal portrait work'],
    related: ['black-grey-tattoos', 'custom-tattoos', 'sleeve-tattoos'],
  },
  {
    slug: 'religious-tattoos',
    name: 'Religious Tattoos',
    title: 'Religious Tattoos in Gurugram',
    metaTitle: 'Religious Tattoo Artist Gurugram | Divine Ink',
    description: 'Plan a respectful religious tattoo in Gurugram with composition, symbolism and placement guidance at Divine Ink Tattoos, Sector 31.',
    eyebrow: 'Respectful symbolism · thoughtful composition',
    intro: 'Religious tattoos carry personal meaning, so symbols, expressions, gestures and accompanying text must be handled deliberately.',
    overview: 'We discuss the spiritual reference and the visual elements that matter most before composing the artwork. Deity portraits, sacred symbols, scripture and ornamental details are balanced for the selected body area.',
    planning: tattooConsultation,
    care: 'Detailed devotional imagery generally needs more space than a simple symbol. The artist will explain when reducing the design would compromise faces, hands, lettering or ornament.',
    highlights: ['Meaning-led design consultation', 'Sacred symbols and devotional imagery', 'Script and ornament integration', 'Respectful placement discussion'],
    related: ['portrait-tattoos', 'black-grey-tattoos', 'colour-tattoos'],
  },
  {
    slug: 'cover-up-tattoos',
    name: 'Cover Up Tattoos',
    title: 'Cover Up Tattoos in Gurugram',
    metaTitle: 'Cover Up Tattoo Artist Gurugram | Divine Ink',
    description: 'Get a cover-up tattoo assessment in Gurugram. Divine Ink reviews the existing tattoo and plans realistic coverage from Sector 31.',
    eyebrow: 'Assessment first · realistic coverage',
    intro: 'A successful cover-up is designed around the darkness, size and position of the existing tattoo—not simply placed over it.',
    overview: 'Send clear, unfiltered photographs in natural light for an initial assessment. We examine the darkest areas, scar tissue, faded sections and available surrounding space before recommending a direction.',
    planning: 'The new design usually needs to be larger and strategically darker than the old tattoo. In some cases, lightening or removal sessions may create better options before cover-up work begins.',
    care: 'Final feasibility is confirmed in person because skin texture and old pigment can look different from photographs. We will not promise complete coverage when the existing tattoo cannot support it.',
    highlights: ['Photo and in-person assessment', 'Dark-area placement strategy', 'Rework or full-cover options', 'Honest feasibility guidance'],
    related: ['black-grey-tattoos', 'custom-tattoos', 'sleeve-tattoos'],
  },
  {
    slug: 'sleeve-tattoos',
    name: 'Sleeve Tattoos',
    title: 'Sleeve Tattoos in Gurugram',
    metaTitle: 'Sleeve Tattoo Artist in Gurugram | Divine Ink',
    description: 'Plan a sleeve tattoo in Gurugram with composition mapping, session scheduling and style direction at Divine Ink Tattoos, Sector 31.',
    eyebrow: 'Full-arm flow · planned sessions',
    intro: 'A sleeve should read as one composition around the arm instead of a collection of disconnected images filling empty spaces.',
    overview: 'We map primary subjects, transitions, background and open skin around the shoulder, elbow and forearm. Existing tattoos can sometimes be incorporated, but their style and placement affect the overall plan.',
    planning: 'Sleeves are normally completed across multiple sessions. The sequence considers design priority, healing time, available appointment length and whether the work is black-and-grey or colour.',
    care: 'Begin with a clear theme and identify any subjects that must be included. Planning the complete sleeve early reduces awkward gaps and conflicting scale later.',
    highlights: ['Complete arm composition mapping', 'Existing tattoo integration review', 'Multi-session scheduling', 'Consistent style and background planning'],
    related: ['black-grey-tattoos', 'colour-tattoos', 'custom-tattoos'],
  },
  {
    slug: 'minimal-tattoos',
    name: 'Minimal Tattoos',
    title: 'Minimal Tattoos in Gurugram',
    metaTitle: 'Minimal Tattoo Artist Gurugram | Divine Ink',
    description: 'Book a minimal tattoo in Gurugram with clean design, suitable sizing and placement guidance at Divine Ink Tattoos in Sector 31.',
    eyebrow: 'Simple forms · intentional placement',
    intro: 'Minimal tattoos look effortless only when line weight, negative space and placement have been considered carefully.',
    overview: 'We simplify references to their essential shape and remove details that would not remain readable at the requested size. Symbols, small florals, geometric marks and understated lettering can all be adapted.',
    planning: tattooConsultation,
    care: 'Small does not always mean suitable for every detail. We recommend adjustments when a concept needs more space or stronger line separation to heal cleanly.',
    highlights: ['Clean simplified artwork', 'Small-scale readability checks', 'Discrete placement options', 'Symbols, florals and geometric designs'],
    related: ['fine-line-tattoos', 'name-tattoos', 'custom-tattoos'],
  },
  {
    slug: 'ear-piercing',
    name: 'Ear Piercing',
    title: 'Ear Piercing in Gurugram',
    metaTitle: 'Professional Ear Piercing Gurugram | Divine Ink',
    description: 'Book professional ear piercing in Gurugram with anatomy-led placement and aftercare guidance at Divine Ink Studio, Sector 31.',
    eyebrow: 'Lobe and cartilage placement',
    intro: 'Ear piercing placement should suit your ear anatomy, jewellery plan and the way you sleep, work and use headphones.',
    overview: 'Divine Ink offers appointment-led consultation for lobe and suitable cartilage placements. We discuss spacing for single or multiple piercings and explain why not every ear supports every reference layout.',
    planning: piercingConsultation,
    care: 'Healing time varies by placement, with cartilage generally requiring more patience than lobes. Avoid unnecessary touching and follow the cleaning guidance provided at the appointment.',
    highlights: ['Lobe and suitable cartilage assessment', 'Balanced multiple-piercing spacing', 'Fresh piercing consumables', 'Clear healing and cleaning guidance'],
    related: ['industrial-piercing', 'nose-piercing', 'eyebrow-piercing'],
  },
  {
    slug: 'nose-piercing',
    name: 'Nose Piercing',
    title: 'Nose Piercing in Gurugram',
    metaTitle: 'Professional Nose Piercing Gurugram | Divine Ink',
    description: 'Book a hygienic nose piercing in Gurugram with placement assessment and practical aftercare at Divine Ink Studio in Sector 31.',
    eyebrow: 'Balanced placement · practical aftercare',
    intro: 'Nose piercing placement is chosen around your anatomy, preferred side and the jewellery style you may want after healing.',
    overview: 'The piercer marks the position for review before proceeding. We consider facial balance and avoid copying a placement that does not suit the individual nostril shape.',
    planning: piercingConsultation,
    care: 'Do not change jewellery prematurely or repeatedly rotate a healing piercing. Follow the provided cleaning routine and contact the studio if healing concerns develop.',
    highlights: ['Individual nostril assessment', 'Placement marking before piercing', 'Hygiene-focused appointment', 'Jewellery-change timing guidance'],
    related: ['ear-piercing', 'eyebrow-piercing', 'belly-piercing'],
  },
  {
    slug: 'belly-piercing',
    name: 'Belly Piercing',
    title: 'Belly Piercing in Gurugram',
    metaTitle: 'Professional Belly Piercing Gurugram | Divine Ink',
    description: 'Book belly button piercing in Gurugram with anatomy assessment, hygienic procedure and aftercare guidance at Divine Ink, Sector 31.',
    eyebrow: 'Anatomy assessment · careful healing',
    intro: 'A navel piercing should only proceed when the anatomy can support suitable placement without excessive pressure or movement.',
    overview: 'We assess the navel shape and how it changes while sitting before confirming feasibility. Clothing, exercise and daily movement can affect comfort during healing and should be considered before booking.',
    planning: piercingConsultation,
    care: 'Choose loose, clean clothing for the appointment and avoid friction over the fresh piercing. Healing requires consistency; jewellery should not be changed simply because the surface looks settled.',
    highlights: ['Navel anatomy suitability check', 'Sitting and movement assessment', 'Hygiene-focused procedure', 'Clothing and aftercare guidance'],
    related: ['ear-piercing', 'nose-piercing', 'eyebrow-piercing'],
  },
  {
    slug: 'eyebrow-piercing',
    name: 'Eyebrow Piercing',
    title: 'Eyebrow Piercing in Gurugram',
    metaTitle: 'Professional Eyebrow Piercing Gurugram | Divine Ink',
    description: 'Book eyebrow piercing in Gurugram with anatomy and placement assessment plus healing guidance at Divine Ink Studio, Sector 31.',
    eyebrow: 'Facial balance · anatomy-led placement',
    intro: 'Eyebrow piercing placement needs enough suitable tissue and should be planned around facial balance rather than a fixed template.',
    overview: 'We mark the entry and exit points for review and explain the possibility of migration or rejection associated with surface-adjacent placements. Suitability is assessed before the procedure.',
    planning: piercingConsultation,
    care: 'Protect the area from snagging on towels, clothing and grooming tools. Follow the cleaning routine and avoid changing jewellery before the piercing has stabilised.',
    highlights: ['Tissue suitability assessment', 'Entry and exit point marking', 'Migration-risk explanation', 'Snag prevention and aftercare'],
    related: ['nose-piercing', 'ear-piercing', 'industrial-piercing'],
  },
  {
    slug: 'industrial-piercing',
    name: 'Industrial Piercing',
    title: 'Industrial Piercing in Gurugram',
    metaTitle: 'Industrial Ear Piercing Gurugram | Divine Ink',
    description: 'Get an industrial piercing suitability assessment in Gurugram with placement and aftercare guidance at Divine Ink, Sector 31.',
    eyebrow: 'Ear anatomy · aligned placement',
    intro: 'Industrial piercing connects two cartilage piercings with one bar, so the ear must support both points in a safe, aligned position.',
    overview: 'Not every ear has the ridge shape or clearance required for an industrial. We assess anatomy rather than forcing a reference placement that could create pressure against the flat of the ear.',
    planning: piercingConsultation,
    care: 'Industrial piercings can be sensitive to sleeping pressure and accidental knocks. Healing requires patience, careful cleaning and avoiding headphones or habits that irritate the area.',
    highlights: ['Two-point alignment assessment', 'Ear ridge and clearance check', 'Pressure-risk explanation', 'Long-term cartilage aftercare'],
    related: ['ear-piercing', 'eyebrow-piercing', 'nose-piercing'],
  },
];

export const servicePageMap = new Map(
  servicePages.map((service) => [service.slug, service]),
);
